# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipelie-to-AWS-ElasticBeanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "tyler-flask-app"
  EB_APPLICATION_NAME      : "MyFlask"
  EB_ENVIRONMENT_NAME      : "Myflask-env"
  DEPLOY_PACKAGE_NAME      : "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-east-1"


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  

  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    my_ci_pipeline:
      runs-on: [ubuntu_latest]
       

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        
        - name: Git clone our repository 
          uses: actions/checkout@v1
  
        - name: create ZIP deployment package
          run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
  
        - name: configure my aws credentils 
          uses: aws-actions/configure-aws-credentils@v1
          with: 
            aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
            aws-secret-key-id : ${{ secrets.MY_AWS_SECRET_KEY }}
            aws-region        : ${{ env.AWS_REGION_NAME }} 
        
        - name : copy our deployment package to s3 bucket
          run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/

        - name: print the nice mesage on completion of CI Pipeline 
          run: echo "CI pipeline part finihed succesfully"
